spring:
  application:
    name: impulse    # 项目名称尽量用小写
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-m5e7x039d1rj7k336po.mysql.rds.aliyuncs.com:3306/huanyu_admin_dev?characterEncoding=utf-8&useSSL=false&useCursorFetch=true&allowPublicKeyRetrieval=true
      username: hyzg
      password: Hyzg8888
  data:
     mongodb:
       custom:
        hosts:
        - 47.105.55.134
        ports:
           - 8060
        database: huanyu_admin_dev
        username: hyzg_dev
        password: hyzg8888
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8

mybatis:
  typeAliasesPackage: com.msp.impluse.entity.*
  mapperLocations: classpath:/mapper/*.xml  #指定*Mapper.xml的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8072
  session:
    timeout:3600
  undertow:
    io-threads: 4
    worker-threads: 300

logging:
  level:
    root: INFO
  file: impulse.log

nb:
  platformIp: 180.101.147.89
  platformPort: 8743
  appId: zP_FVj4ytNsqYGiakgFmWwMO_hga
  secret: CkOFfYserdkJvoXeERe__P0unlMa
  manufacturerId: hyzg
  manufacturerName: hyzg
  dataCallbackUrl: http://47.105.55.134:8072/v1.0.0/messageReceiver

