spring:
  application:
    name: impulse    # 项目名称尽量用小写
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-m5e7x039d1rj7k336.mysql.rds.aliyuncs.com:3306/huanyu_admin?characterEncoding=utf-8&useSSL=false&useCursorFetch=true&allowPublicKeyRetrieval=true
      username: hyzg
      password: Hyzg8888
  data:
    mongodb:
      custom:
        hosts:
        - dds-m5ea5feb0705bd541.mongodb.rds.aliyuncs.com
        - dds-m5ea5feb0705bd542.mongodb.rds.aliyuncs.com
        ports:
        - 3717
        - 3717
        database: huanyu
        username: root
        password: Hyzg8888
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null

mybatis:
  typeAliasesPackage: com.msp.impluse.entity.*
  mapperLocations: classpath:/mapper/*.xml  #指定*Mapper.xml的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8072
  session:
    timeout:3600

logging:
  level:
    root: INFO
  file: impulse.log


