spring:
  application:
    name: impulse    # 项目名称尽量用小写
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://rm-8vb9q0m9d1vtweygu.mysql.zhangbei.rds.aliyuncs.com:3306/huanyu_admin?characterEncoding=utf-8&useSSL=false&useCursorFetch=true
      username: bht
      password:  bht_2018
  data:
    mongodb:
      custom:
        hosts:
        -  dds-8vbce58e780028c41.mongodb.zhangbei.rds.aliyuncs.com
        ports:
        - 3717
        database: admin
        username: root
        password: bht_2018
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null

mybatis:
  typeAliasesPackage: com.msp.impluse.entity.*
  mapperLocations: classpath:/mapper/*.xml  #指定*Mapper.xml的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8072
  session:
    timeout:3600

logging:
  level:
    root: INFO
  file: impulse.log


