spring:
  application:
    name: impulse    # 项目名称尽量用小写
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://39.105.86.90/huanyu_admin?characterEncoding=utf-8&useSSL=false&useCursorFetch=true
      username: root
      password: 12345678
  data:
    mongodb:
      custom:
        hosts:
        - 39.105.86.90
        ports:
        - 27017
        database: huanyu
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null

mybatis:
  typeAliasesPackage: com.msp.impluse.entity.*
  mapperLocations: classpath:/mapper/*.xml  #指定*Mapper.xml的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080

logging:
  level:
    root: INFO
  file: impulse.log


